/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    services: Service;
    'service-pages': ServicePage;
    subclasses: Subclass;
    situations: Situation;
    faqs: Faq;
    testimonials: Testimonial;
    'case-studies': CaseStudy;
    'processing-times': ProcessingTime;
    'pinned-reviews': PinnedReview;
    'success-stories': SuccessStory;
    leads: Lead;
    consultations: Consultation;
    redirects: Redirect;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-pages': ServicePagesSelect<false> | ServicePagesSelect<true>;
    subclasses: SubclassesSelect<false> | SubclassesSelect<true>;
    situations: SituationsSelect<false> | SituationsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'processing-times': ProcessingTimesSelect<false> | ProcessingTimesSelect<true>;
    'pinned-reviews': PinnedReviewsSelect<false> | PinnedReviewsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    consultations: ConsultationsSelect<false> | ConsultationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    homepage: Homepage;
    settings: Setting;
    navigation: Navigation;
    footer: Footer;
    'social-media': SocialMedia;
    disclaimers: Disclaimer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'social-media': SocialMediaSelect<false> | SocialMediaSelect<true>;
    disclaimers: DisclaimersSelect<false> | DisclaimersSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'agent' | 'client';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and files used across the website. Always add descriptive alt text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image. Use alt="" only for purely decorative media.
   */
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog posts and resource articles. Draft, then set status to Published to go live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  category:
    | 'guide'
    | 'migration-news'
    | 'employer-hub'
    | 'student-hub'
    | 'partner-visa-hub'
    | 'visitor-visa-hub'
    | 'refusals-appeals'
    | 'moving-to-perth'
    | 'case-study';
  status: 'draft' | 'scheduled' | 'published';
  featured?: boolean | null;
  /**
   * Set automatically on first publish. Never changes.
   */
  publishedAt?: string | null;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?: string[] | null;
  /**
   * Optional Q&A. Rendered on the article and emitted as FAQ schema.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Minutes. Leave blank to auto-estimate from the content.
   */
  readingTime?: number | null;
  author?: (number | null) | User;
  relatedArticles?: (number | Article)[] | null;
  relatedSubclasses?: (number | Subclass)[] | null;
  /**
   * Freshness + author accountability. Verify on every legal change.
   */
  reviewedBy?: {
    lastReviewedAt?: string | null;
    reviewer?: (number | null) | User;
    marn?: string | null;
  };
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subclasses".
 */
export interface Subclass {
  id: number;
  /**
   * e.g. 190, 482, 820/801
   */
  code: string;
  name: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  service?: (number | null) | Service;
  /**
   * One-line hero value proposition.
   */
  valueProposition?: string | null;
  plainOneLiner?: string | null;
  atAGlance?: {
    visaType?: ('permanent' | 'temporary' | 'provisional' | 'bridging') | null;
    costRange?: string | null;
    processingTime?: string | null;
    duration?: string | null;
    onshoreOffshore?: ('onshore' | 'offshore' | 'either') | null;
    pointsNeeded?: string | null;
  };
  /**
   * Renders ONLY with a verified amount + as-at date + source. Never estimate.
   */
  governmentFee?: {
    amount?: string | null;
    asAt?: string | null;
    sourceUrl?: string | null;
  };
  complexity?: {
    level?: ('straightforward' | 'moderate' | 'complex') | null;
    /**
     * General guidance, not a prediction.
     */
    note?: string | null;
  };
  overview?: {
    whatItIs?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    whoItIsFor?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    whyThisPathway?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  eligibility?:
    | {
        title?: string | null;
        items?:
          | {
              requirement?: string | null;
              detail?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  benefits?: {
    permanentResidency?: boolean | null;
    familyInclusion?: boolean | null;
    workRights?: boolean | null;
    studyRights?: boolean | null;
    medicare?: boolean | null;
    travelRights?: boolean | null;
    custom?:
      | {
          title?: string | null;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  process?:
    | {
        stepTitle?: string | null;
        description?: string | null;
        estimatedDuration?: string | null;
        documents?:
          | {
              doc?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        category?: string | null;
        items?:
          | {
              name?: string | null;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  costs?: {
    professionalFeeEnabled?: boolean | null;
    professionalFeeRange?: string | null;
    notes?: string | null;
  };
  commonMistakes?:
    | {
        title?: string | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  whatGoesWrong?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  isThisYou?:
    | {
        check?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?: (number | Faq)[] | null;
  relatedResources?: (number | Article)[] | null;
  relatedServices?: (number | Service)[] | null;
  /**
   * For "related visa" recommendations + comparison pages.
   */
  relatedVisas?: (number | Subclass)[] | null;
  featuredTestimonials?: (number | Testimonial)[] | null;
  featuredReviews?: (number | PinnedReview)[] | null;
  /**
   * Freshness + author accountability. Verify on every legal change.
   */
  reviewedBy?: {
    lastReviewedAt?: string | null;
    reviewer?: (number | null) | User;
    marn?: string | null;
  };
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  valueProposition?: string | null;
  summary?: string | null;
  heroIllustration?: (number | null) | Media;
  personas?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  whyChoose?: {
    benefits?:
      | {
          title?: string | null;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
    typicalOutcomes?: string | null;
    /**
     * Honest limitations — on brand.
     */
    considerations?: string | null;
  };
  journey?:
    | {
        title?: string | null;
        description?: string | null;
        linkedSubclass?: (number | null) | Subclass;
        id?: string | null;
      }[]
    | null;
  whatGoesWrong?: string | null;
  situation?: (number | null) | Situation;
  faqs?: (number | Faq)[] | null;
  relatedResources?: (number | Article)[] | null;
  relatedServices?: (number | Service)[] | null;
  featuredReviews?: (number | PinnedReview)[] | null;
  /**
   * Freshness + author accountability. Verify on every legal change.
   */
  reviewedBy?: {
    lastReviewedAt?: string | null;
    reviewer?: (number | null) | User;
    marn?: string | null;
  };
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "situations".
 */
export interface Situation {
  id: number;
  key:
    | 'skilled-professional'
    | 'student'
    | 'partnered-to-australian'
    | 'employer'
    | 'visa-refused'
    | 'bridging-visa';
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  empathyLine?: string | null;
  destinationService?: (number | null) | Service;
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  subclass?: (number | null) | Subclass;
  order?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pinned-reviews".
 */
export interface PinnedReview {
  id: number;
  reviewerName: string;
  rating?: number | null;
  text?: string | null;
  googleReviewUrl?: string | null;
  pinnedOrder?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  situation?: string | null;
  subclass?: (number | null) | Subclass;
  date?: string | null;
  quote: string;
  /**
   * Publish only with recorded consent.
   */
  consentRecorded: boolean;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The "Our Services" pages (visa and service pages shown on the website). Edit the hero, body, FAQ, CTA and SEO here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-pages".
 */
export interface ServicePage {
  id: number;
  title: string;
  slug: string;
  section: 'visas' | 'services' | 'root';
  status: 'draft' | 'scheduled' | 'published';
  featured?: boolean | null;
  /**
   * Hero subtitle / lead.
   */
  subtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Card + Open Graph image.
   */
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Verbatim "Related:" labels from the source document.
   */
  relatedLinks?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional resolved internal links for the related labels.
   */
  relatedServices?: (number | ServicePage)[] | null;
  /**
   * Optional. Only shown when provided.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    heading?: string | null;
    /**
     * Verbatim CTA paragraph.
     */
    body?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  disclaimer?: string | null;
  /**
   * Set automatically on first publish. Never changes.
   */
  publishedAt?: string | null;
  /**
   * Minutes. Leave blank to auto-estimate from the content.
   */
  readingTime?: number | null;
  author?: (number | null) | User;
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  subclass?: (number | null) | Subclass;
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  consentRecorded: boolean;
  status?: ('draft' | 'published') | null;
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processing-times".
 */
export interface ProcessingTime {
  id: number;
  subclassCode: string;
  /**
   * e.g. "8–12 months". Empty renders as em-dash.
   */
  currentEstimate?: string | null;
  /**
   * Home Affairs source, linked on the page.
   */
  sourceUrl?: string | null;
  lastVerifiedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  title: string;
  status: 'draft' | 'published';
  type:
    | 'review-video'
    | 'testimonial-video'
    | 'client-photo'
    | 'grant-letter'
    | 'written-testimonial'
    | 'success-story';
  category: 'employer-sponsored' | 'student' | 'partner' | 'skilled' | 'visitor' | 'other';
  /**
   * Short supporting line shown under the title.
   */
  description?: string | null;
  /**
   * The testimonial or story text (written types).
   */
  quote?: string | null;
  /**
   * Optional display name — only with the client’s permission.
   */
  clientName?: string | null;
  /**
   * Client photo or REDACTED grant letter image.
   */
  image?: (number | null) | Media;
  /**
   * YouTube or Vimeo URL for video types.
   */
  videoUrl?: string | null;
  /**
   * REQUIRED before this appears publicly: the client has given permission to publish this content. The website only shows entries with consent ticked.
   */
  consent?: boolean | null;
  featured?: boolean | null;
  /**
   * Display order within its carousel (lower shows first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Globally-unique, human-friendly reference: VMD-YYYYMMDD-NNNNNN.
   */
  submissionId?: string | null;
  source:
    | 'health-check'
    | 'second-opinion'
    | 'consultation'
    | 'guide-download'
    | 'newsletter'
    | 'quick-enquiry'
    | 'general-enquiry';
  firstName: string;
  email: string;
  mobile?: string | null;
  situation?: string | null;
  country?: string | null;
  nationality?: string | null;
  currentVisa?: string | null;
  goal?: string | null;
  message?: string | null;
  score?: number | null;
  status?: ('new' | 'contacted' | 'qualified' | 'booked' | 'won' | 'lost') | null;
  assignedTo?: (number | null) | User;
  /**
   * Structured Health Check answers.
   */
  healthCheck?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  attribution?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    landingPage?: string | null;
    referrer?: string | null;
    device?: string | null;
  };
  marketingConsent?: boolean | null;
  /**
   * CRM sync state (e.g. HubSpot). Written by the sync, not by staff.
   */
  crm?: {
    provider?: string | null;
    contactId?: string | null;
    syncedAt?: string | null;
    status?: ('pending' | 'synced' | 'skipped' | 'error') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations".
 */
export interface Consultation {
  id: number;
  type: 'initial' | 'second-opinion' | 'follow-up' | 'standard' | 'online' | 'in-person';
  firstName: string;
  email: string;
  mobile: string;
  requestedStartUtc?: string | null;
  timezone?: string | null;
  notes?: string | null;
  status: 'requested' | 'confirmed' | 'rescheduled' | 'completed' | 'cancelled' | 'no_show';
  providerRef?: string | null;
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  code?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete';
  collectionSlug: string;
  docId: string;
  user?: (number | null) | User;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-pages';
        value: number | ServicePage;
      } | null)
    | ({
        relationTo: 'subclasses';
        value: number | Subclass;
      } | null)
    | ({
        relationTo: 'situations';
        value: number | Situation;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'processing-times';
        value: number | ProcessingTime;
      } | null)
    | ({
        relationTo: 'pinned-reviews';
        value: number | PinnedReview;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'consultations';
        value: number | Consultation;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  status?: T;
  featured?: T;
  publishedAt?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  tags?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  readingTime?: T;
  author?: T;
  relatedArticles?: T;
  relatedSubclasses?: T;
  reviewedBy?:
    | T
    | {
        lastReviewedAt?: T;
        reviewer?: T;
        marn?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  valueProposition?: T;
  summary?: T;
  heroIllustration?: T;
  personas?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whyChoose?:
    | T
    | {
        benefits?:
          | T
          | {
              title?: T;
              detail?: T;
              id?: T;
            };
        typicalOutcomes?: T;
        considerations?: T;
      };
  journey?:
    | T
    | {
        title?: T;
        description?: T;
        linkedSubclass?: T;
        id?: T;
      };
  whatGoesWrong?: T;
  situation?: T;
  faqs?: T;
  relatedResources?: T;
  relatedServices?: T;
  featuredReviews?: T;
  reviewedBy?:
    | T
    | {
        lastReviewedAt?: T;
        reviewer?: T;
        marn?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-pages_select".
 */
export interface ServicePagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  section?: T;
  status?: T;
  featured?: T;
  subtitle?: T;
  heroImage?: T;
  featuredImage?: T;
  content?: T;
  relatedLinks?:
    | T
    | {
        label?: T;
        id?: T;
      };
  relatedServices?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        body?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  disclaimer?: T;
  publishedAt?: T;
  readingTime?: T;
  author?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subclasses_select".
 */
export interface SubclassesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  slug?: T;
  status?: T;
  service?: T;
  valueProposition?: T;
  plainOneLiner?: T;
  atAGlance?:
    | T
    | {
        visaType?: T;
        costRange?: T;
        processingTime?: T;
        duration?: T;
        onshoreOffshore?: T;
        pointsNeeded?: T;
      };
  governmentFee?:
    | T
    | {
        amount?: T;
        asAt?: T;
        sourceUrl?: T;
      };
  complexity?:
    | T
    | {
        level?: T;
        note?: T;
      };
  overview?:
    | T
    | {
        whatItIs?: T;
        whoItIsFor?: T;
        whyThisPathway?: T;
      };
  eligibility?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              requirement?: T;
              detail?: T;
              id?: T;
            };
        id?: T;
      };
  benefits?:
    | T
    | {
        permanentResidency?: T;
        familyInclusion?: T;
        workRights?: T;
        studyRights?: T;
        medicare?: T;
        travelRights?: T;
        custom?:
          | T
          | {
              title?: T;
              detail?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        stepTitle?: T;
        description?: T;
        estimatedDuration?: T;
        documents?:
          | T
          | {
              doc?: T;
              id?: T;
            };
        id?: T;
      };
  documents?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              name?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  costs?:
    | T
    | {
        professionalFeeEnabled?: T;
        professionalFeeRange?: T;
        notes?: T;
      };
  commonMistakes?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  whatGoesWrong?:
    | T
    | {
        item?: T;
        id?: T;
      };
  isThisYou?:
    | T
    | {
        check?: T;
        id?: T;
      };
  faqs?: T;
  relatedResources?: T;
  relatedServices?: T;
  relatedVisas?: T;
  featuredTestimonials?: T;
  featuredReviews?: T;
  reviewedBy?:
    | T
    | {
        lastReviewedAt?: T;
        reviewer?: T;
        marn?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "situations_select".
 */
export interface SituationsSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  slug?: T;
  status?: T;
  empathyLine?: T;
  destinationService?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  subclass?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  situation?: T;
  subclass?: T;
  date?: T;
  quote?: T;
  consentRecorded?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subclass?: T;
  problem?: T;
  approach?: T;
  outcome?: T;
  consentRecorded?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processing-times_select".
 */
export interface ProcessingTimesSelect<T extends boolean = true> {
  subclassCode?: T;
  currentEstimate?: T;
  sourceUrl?: T;
  lastVerifiedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pinned-reviews_select".
 */
export interface PinnedReviewsSelect<T extends boolean = true> {
  reviewerName?: T;
  rating?: T;
  text?: T;
  googleReviewUrl?: T;
  pinnedOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  type?: T;
  category?: T;
  description?: T;
  quote?: T;
  clientName?: T;
  image?: T;
  videoUrl?: T;
  consent?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  submissionId?: T;
  source?: T;
  firstName?: T;
  email?: T;
  mobile?: T;
  situation?: T;
  country?: T;
  nationality?: T;
  currentVisa?: T;
  goal?: T;
  message?: T;
  score?: T;
  status?: T;
  assignedTo?: T;
  healthCheck?: T;
  attribution?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        landingPage?: T;
        referrer?: T;
        device?: T;
      };
  marketingConsent?: T;
  crm?:
    | T
    | {
        provider?: T;
        contactId?: T;
        syncedAt?: T;
        status?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations_select".
 */
export interface ConsultationsSelect<T extends boolean = true> {
  type?: T;
  firstName?: T;
  email?: T;
  mobile?: T;
  requestedStartUtc?: T;
  timezone?: T;
  notes?: T;
  status?: T;
  providerRef?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  docId?: T;
  user?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every section of the home page, top to bottom. Open a tab to edit that section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    /**
     * The paragraph under the headline.
     */
    lead?: string | null;
    /**
     * Button text and where it links to.
     */
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Button text and where it links to.
     */
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  situations?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Each card links a visitor to their situation hub.
     */
    items?:
      | {
          label: string;
          description: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  whyChoose?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    promises?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  successStories?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Button text and where it links to.
     */
    link?: {
      label?: string | null;
      href?: string | null;
    };
  };
  featuredServices?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Button text and where it links to.
     */
    seeAll?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Button text and where it links to.
     */
    secondaryLink?: {
      label?: string | null;
      href?: string | null;
    };
  };
  howWeWork?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    steps?:
      | {
          label: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  practitioner?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    body?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Button text and where it links to.
     */
    button?: {
      label?: string | null;
      href?: string | null;
    };
  };
  googleReviews?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Google exposes up to 5 of the latest reviews.
     */
    count?: number | null;
  };
  featuredBlogs?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * Button text and where it links to.
     */
    link?: {
      label?: string | null;
      href?: string | null;
    };
  };
  faqs?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    intro?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  finalCta?: {
    /**
     * Show this section on the live page. Uncheck to hide it entirely.
     */
    show?: boolean | null;
    heading?: string | null;
    lead?: string | null;
    buttonLabel?: string | null;
    promise?: string | null;
  };
  /**
   * Search + social metadata. Human-written, unique per page.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noindex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  googleReviews?: {
    rating?: number | null;
    count?: number | null;
    profileUrl?: string | null;
  };
  whatsappNumber?: string | null;
  bookingEnabled?: boolean | null;
  /**
   * The Client Portal button in the site navigation.
   */
  clientPortal?: {
    enabled?: boolean | null;
    label?: string | null;
    url?: string | null;
    /**
     * Optional hex colour (e.g. #2589BA). Leave blank to use the brand blue. Non-hex values are ignored.
     */
    color?: string | null;
  };
  /**
   * Where the two site-wide call-to-action buttons point.
   */
  ctaLinks?: {
    /**
     * Primary CTA — "Book a Consultation".
     */
    bookConsultationUrl?: string | null;
    /**
     * Secondary CTA — "Free Visa Health Check".
     */
    healthCheckUrl?: string | null;
  };
  /**
   * Deep link to the Migration Manager practice system (client portal integration).
   */
  migrationManagerUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The link columns in the site footer. The address, phone and legal line come from Global Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Each column has a heading and a list of links. Leave empty to use the site defaults.
   */
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Links to your social profiles. Blank fields simply hide that icon on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media".
 */
export interface SocialMedia {
  id: number;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  tiktok?: string | null;
  youtube?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimers".
 */
export interface Disclaimer {
  id: number;
  outcomes?: string | null;
  generalInformation?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  situations?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              label?: T;
              description?: T;
              href?: T;
              id?: T;
            };
      };
  whyChoose?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        promises?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  successStories?:
    | T
    | {
        show?: T;
        eyebrow?: T;
        heading?: T;
        intro?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  featuredServices?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        seeAll?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryLink?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  howWeWork?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        steps?:
          | T
          | {
              label?: T;
              description?: T;
              id?: T;
            };
      };
  practitioner?:
    | T
    | {
        show?: T;
        eyebrow?: T;
        heading?: T;
        body?:
          | T
          | {
              text?: T;
              id?: T;
            };
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  googleReviews?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        count?: T;
      };
  featuredBlogs?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  faqs?:
    | T
    | {
        show?: T;
        heading?: T;
        intro?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        show?: T;
        heading?: T;
        lead?: T;
        buttonLabel?: T;
        promise?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noindex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  googleReviews?:
    | T
    | {
        rating?: T;
        count?: T;
        profileUrl?: T;
      };
  whatsappNumber?: T;
  bookingEnabled?: T;
  clientPortal?:
    | T
    | {
        enabled?: T;
        label?: T;
        url?: T;
        color?: T;
      };
  ctaLinks?:
    | T
    | {
        bookConsultationUrl?: T;
        healthCheckUrl?: T;
      };
  migrationManagerUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
  facebook?: T;
  instagram?: T;
  linkedin?: T;
  tiktok?: T;
  youtube?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disclaimers_select".
 */
export interface DisclaimersSelect<T extends boolean = true> {
  outcomes?: T;
  generalInformation?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
