/**
 * Token build. Emits dist/tokens.css (:root custom properties) and enforces the
 * accessibility guarantees at BUILD TIME. A violation exits non-zero -> the
 * platform does not build. This is Blueprint §11.1 / ARCHITECTURE.md §4.3 made real.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { palette, colorTokens } from './src/color.ts';
import { contrastRatio, round2 } from './src/contrast.ts';
import { typeScale, fontFamilies } from './src/type.ts';
import { space, container } from './src/space.ts';
import { shadow } from './src/shadow.ts';
import { radius } from './src/radius.ts';
import { duration, easing } from './src/motion.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WHITE = palette.white;
const NAVY = palette.navy;

const errors: string[] = [];

// GATE 1 — every text-on-light token clears AA (4.5:1) on white.
for (const [name, def] of Object.entries(colorTokens)) {
  if (def.intent === 'text-on-light') {
    const r = contrastRatio(def.value, WHITE);
    if (r < 4.5) errors.push(`${name} (${def.value}) is ${round2(r)}:1 on white — below AA 4.5:1.`);
  }
  if (def.intent === 'text-on-dark') {
    const r = contrastRatio(def.value, NAVY);
    if (r < 4.5) errors.push(`${name} (${def.value}) is ${round2(r)}:1 on navy — below AA 4.5:1.`);
  }
}

// GATE 2 — gold and azure must NEVER be declared as text-on-light. This is the
// specific failure mode the whole system exists to prevent.
for (const [name, def] of Object.entries(colorTokens)) {
  if (def.intent === 'text-on-light' && (def.value === palette.gold || def.value === palette.azure)) {
    errors.push(`${name} maps ${def.value} to a light-text role. Gold/Azure fail on white. Forbidden.`);
  }
}

// GATE 3 — sanity: the known brand facts must hold (catches an accidental hex edit).
const goldOnWhite = round2(contrastRatio(palette.gold, WHITE));
if (goldOnWhite >= 4.5) errors.push(`Gold on white is now ${goldOnWhite}:1 — palette changed unexpectedly.`);

if (errors.length) {
  console.error('\n✖ Token contrast gate FAILED:\n' + errors.map((e) => `  - ${e}`).join('\n') + '\n');
  process.exit(1);
}

// ---- emit CSS ----
const lines: string[] = [
  '/* GENERATED by @vmd/tokens build.ts — do not edit by hand. */',
  ':root {',
  '  /* colour */',
];
for (const [name, def] of Object.entries(colorTokens)) lines.push(`  --${name}: ${def.value};`);
lines.push('', '  /* type */');
lines.push(`  --font-display: ${fontFamilies.display};`);
lines.push(`  --font-body: ${fontFamilies.body};`);
lines.push('  --type-base: 17px;');
for (const [name, s] of Object.entries(typeScale)) {
  const mSize = s.mobile[0];
  const dSize = s.desktop[0];
  const min = Math.min(mSize, dSize);
  const max = Math.max(mSize, dSize);
  const pref = `calc(${mSize}px + ${dSize - mSize} * ((100vw - 390px) / 890))`;
  const leading = round2(s.desktop[1] / s.desktop[0]);
  lines.push(`  --type-${name}: clamp(${min}px, ${pref}, ${max}px); --leading-${name}: ${leading};`);
}
lines.push('', '  /* space (8px grid) */');
for (const [k, v] of Object.entries(space)) lines.push(`  --space-${k}: ${v}px;`);
lines.push(`  --container-max: ${container.max}px; --container-prose: ${container.prose}px; --gutter: ${container.gutter}px;`);
lines.push('', '  /* radius */');
for (const [k, v] of Object.entries(radius)) lines.push(`  --radius-${k}: ${v};`);
lines.push('', '  /* shadow (exactly four) */');
for (const [k, v] of Object.entries(shadow)) lines.push(`  --shadow-${k}: ${v};`);
lines.push('', '  /* motion */');
for (const [k, v] of Object.entries(duration)) lines.push(`  --motion-${k}: ${v};`);
lines.push(`  --ease-standard: ${easing.standard}; --ease-entrance: ${easing.entrance};`);
lines.push('}');
lines.push('');
lines.push('@media (prefers-reduced-motion: reduce) {');
lines.push('  :root { --motion-fast: 0ms; --motion-base: 0ms; --motion-slow: 0ms; }');
lines.push('}');
lines.push('');

const outDir = join(__dirname, 'dist');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'tokens.css'), lines.join('\n'), 'utf8');
writeFileSync(
  join(outDir, 'tokens.ts'),
  `// GENERATED. Re-export of the typed token API for convenience.\nexport * from '../src/index.ts';\n`,
  'utf8',
);

const passGold = round2(contrastRatio(palette.gold, palette.navy));
const passNavy = round2(contrastRatio(palette.navy, WHITE));
console.log('✔ Token contrast gate passed.');
console.log(`  navy on white: ${passNavy}:1 (AAA) · gold on navy: ${passGold}:1 (AA)`);
console.log(`  gold on white: ${goldOnWhite}:1 — correctly excluded from all text roles.`);
console.log('✔ Wrote dist/tokens.css and dist/tokens.ts');
