// AUTO-GENERATED from public/Success Stories/** — real, consented, privacy-safe
// client graphics (client names are redacted in-image). Re-run the optimiser
// after adding files; do not edit by hand.
export interface SuccessMedia {
  slug: string;
  category: 'visa-grant' | 'skills-assessment';
  group: string;
  label: string;
  sub: string;
  preview: string;
  full: string;
  width: number;
  height: number;
  alt: string;
}
export const VISA_GRANTS: SuccessMedia[] = [
  {
    slug: 'general-skilled-migration-2026-07-09-sc190-instagram',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-2026-07-09-sc190-instagram.webp',
    full: '/success-stories/full/general-skilled-migration-2026-07-09-sc190-instagram.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-2026-07-10-instagram-sc491',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 491',
    sub: 'Skilled Work Regional',
    preview: '/success-stories/preview/general-skilled-migration-2026-07-10-instagram-sc491.webp',
    full: '/success-stories/full/general-skilled-migration-2026-07-10-instagram-sc491.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 491 (Skilled Work Regional). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-2026-07-22-instagram-sc189',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 189',
    sub: 'Skilled Independent',
    preview: '/success-stories/preview/general-skilled-migration-2026-07-22-instagram-sc189.webp',
    full: '/success-stories/full/general-skilled-migration-2026-07-22-instagram-sc189.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 189 (Skilled Independent). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-2026-07-22-instagram-sc190',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-2026-07-22-instagram-sc190.webp',
    full: '/success-stories/full/general-skilled-migration-2026-07-22-instagram-sc190.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-2026-07-31-instagram-sc190',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-2026-07-31-instagram-sc190.webp',
    full: '/success-stories/full/general-skilled-migration-2026-07-31-instagram-sc190.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-2026-07-31-instagram-sc491',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 491',
    sub: 'Skilled Work Regional',
    preview: '/success-stories/preview/general-skilled-migration-2026-07-31-instagram-sc491.webp',
    full: '/success-stories/full/general-skilled-migration-2026-07-31-instagram-sc491.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 491 (Skilled Work Regional). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram190-500-accountant-general-tas-april-18-2025-22jul',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview:
      '/success-stories/preview/general-skilled-migration-instagram190-500-accountant-general-tas-april-18-2025-22jul.webp',
    full: '/success-stories/full/general-skilled-migration-instagram190-500-accountant-general-tas-april-18-2025-22jul.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram190-500-engineering-technologist-tas-april-17-2025-22jul',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview:
      '/success-stories/preview/general-skilled-migration-instagram190-500-engineering-technologist-tas-april-17-2025-22jul.webp',
    full: '/success-stories/full/general-skilled-migration-instagram190-500-engineering-technologist-tas-april-17-2025-22jul.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram190-500-engineering-technologist-tas-april-18-2025-22jul',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview:
      '/success-stories/preview/general-skilled-migration-instagram190-500-engineering-technologist-tas-april-18-2025-22jul.webp',
    full: '/success-stories/full/general-skilled-migration-instagram190-500-engineering-technologist-tas-april-18-2025-22jul.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram491-500-accountant-general-tas-feb-18-2025-22jul',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 491',
    sub: 'Skilled Work Regional',
    preview:
      '/success-stories/preview/general-skilled-migration-instagram491-500-accountant-general-tas-feb-18-2025-22jul.webp',
    full: '/success-stories/full/general-skilled-migration-instagram491-500-accountant-general-tas-feb-18-2025-22jul.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 491 (Skilled Work Regional). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram-sc190-am1',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-instagram-sc190-am1.webp',
    full: '/success-stories/full/general-skilled-migration-instagram-sc190-am1.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram-sc190-ash1',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-instagram-sc190-ash1.webp',
    full: '/success-stories/full/general-skilled-migration-instagram-sc190-ash1.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram-sc190-bhup1',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-instagram-sc190-bhup1.webp',
    full: '/success-stories/full/general-skilled-migration-instagram-sc190-bhup1.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram-sc190-pras1',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 190',
    sub: 'Skilled Nominated',
    preview: '/success-stories/preview/general-skilled-migration-instagram-sc190-pras1.webp',
    full: '/success-stories/full/general-skilled-migration-instagram-sc190-pras1.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 190 (Skilled Nominated). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram-sc491-accountant-general-april18',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 491',
    sub: 'Skilled Work Regional',
    preview:
      '/success-stories/preview/general-skilled-migration-instagram-sc491-accountant-general-april18.webp',
    full: '/success-stories/full/general-skilled-migration-instagram-sc491-accountant-general-april18.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 491 (Skilled Work Regional). Client details redacted.',
  },
  {
    slug: 'general-skilled-migration-instagram-sc491-kr1',
    category: 'visa-grant',
    group: 'General Skilled Migration',
    label: 'Subclass 491',
    sub: 'Skilled Work Regional',
    preview: '/success-stories/preview/general-skilled-migration-instagram-sc491-kr1.webp',
    full: '/success-stories/full/general-skilled-migration-instagram-sc491-kr1.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 491 (Skilled Work Regional). Client details redacted.',
  },
  {
    slug: 'sc485-2026-07-15-instagram-sc4852nd',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 485',
    sub: 'Temporary Graduate',
    preview: '/success-stories/preview/sc485-2026-07-15-instagram-sc4852nd.webp',
    full: '/success-stories/full/sc485-2026-07-15-instagram-sc4852nd.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 485 (Temporary Graduate). Client details redacted.',
  },
  {
    slug: 'sc485-2026-07-20-instagram-sc4852nd',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 485',
    sub: 'Temporary Graduate',
    preview: '/success-stories/preview/sc485-2026-07-20-instagram-sc4852nd.webp',
    full: '/success-stories/full/sc485-2026-07-20-instagram-sc4852nd.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 485 (Temporary Graduate). Client details redacted.',
  },
  {
    slug: 'sc485-2026-08-05-sc485regional-instagram',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 485',
    sub: 'Temporary Graduate',
    preview: '/success-stories/preview/sc485-2026-08-05-sc485regional-instagram.webp',
    full: '/success-stories/full/sc485-2026-08-05-sc485regional-instagram.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 485 (Temporary Graduate). Client details redacted.',
  },
  {
    slug: 'sc485-insta500-21-apr-2026-21-jul-2026',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 500',
    sub: 'Student',
    preview: '/success-stories/preview/sc485-insta500-21-apr-2026-21-jul-2026.webp',
    full: '/success-stories/full/sc485-insta500-21-apr-2026-21-jul-2026.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 500 (Student). Client details redacted.',
  },
  {
    slug: 'sc485-instagram500-21-apr-2026-23-jul-2026',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 500',
    sub: 'Student',
    preview: '/success-stories/preview/sc485-instagram500-21-apr-2026-23-jul-2026.webp',
    full: '/success-stories/full/sc485-instagram500-21-apr-2026-23-jul-2026.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 500 (Student). Client details redacted.',
  },
  {
    slug: 'sc485-instagram500-29-apr-2026-23-jul-2026',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 500',
    sub: 'Student',
    preview: '/success-stories/preview/sc485-instagram500-29-apr-2026-23-jul-2026.webp',
    full: '/success-stories/full/sc485-instagram500-29-apr-2026-23-jul-2026.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 500 (Student). Client details redacted.',
  },
  {
    slug: 'sc485-instagram-500-01-may-2026-23-jul-2026',
    category: 'visa-grant',
    group: 'SC485',
    label: 'Subclass 500',
    sub: 'Student',
    preview: '/success-stories/preview/sc485-instagram-500-01-may-2026-23-jul-2026.webp',
    full: '/success-stories/full/sc485-instagram-500-01-may-2026-23-jul-2026.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 500 (Student). Client details redacted.',
  },
  {
    slug: 'sc500-2026-07-14-instagram-sc500',
    category: 'visa-grant',
    group: 'SC500',
    label: 'Subclass 500',
    sub: 'Student',
    preview: '/success-stories/preview/sc500-2026-07-14-instagram-sc500.webp',
    full: '/success-stories/full/sc500-2026-07-14-instagram-sc500.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 500 (Student). Client details redacted.',
  },
  {
    slug: 'sc500-2026-07-31-instagram-sc500',
    category: 'visa-grant',
    group: 'SC500',
    label: 'Subclass 500',
    sub: 'Student',
    preview: '/success-stories/preview/sc500-2026-07-31-instagram-sc500.webp',
    full: '/success-stories/full/sc500-2026-07-31-instagram-sc500.webp',
    width: 700,
    height: 876,
    alt: 'Visa grant graphic — Subclass 500 (Student). Client details redacted.',
  },
];
export const SKILLS_ASSESSMENTS: SuccessMedia[] = [
  {
    slug: '2026-07-27-instagram-skillsassessment-communityworker',
    category: 'skills-assessment',
    group: 'Skills Assessment',
    label: 'Community Worker',
    sub: '',
    preview: '/success-stories/preview/2026-07-27-instagram-skillsassessment-communityworker.webp',
    full: '/success-stories/full/2026-07-27-instagram-skillsassessment-communityworker.webp',
    width: 700,
    height: 876,
    alt: 'Skills assessment graphic — Community Worker. Client details redacted.',
  },
  {
    slug: '2026-07-30-instagram-communityworker',
    category: 'skills-assessment',
    group: 'Skills Assessment',
    label: 'Community Worker',
    sub: '',
    preview: '/success-stories/preview/2026-07-30-instagram-communityworker.webp',
    full: '/success-stories/full/2026-07-30-instagram-communityworker.webp',
    width: 700,
    height: 876,
    alt: 'Skills assessment graphic — Community Worker. Client details redacted.',
  },
  {
    slug: 'chef-cook-skillsassessment-2026-07-29',
    category: 'skills-assessment',
    group: 'Skills Assessment',
    label: 'Chef & Cook',
    sub: '',
    preview: '/success-stories/preview/chef-cook-skillsassessment-2026-07-29.webp',
    full: '/success-stories/full/chef-cook-skillsassessment-2026-07-29.webp',
    width: 700,
    height: 876,
    alt: 'Skills assessment graphic — Chef & Cook. Client details redacted.',
  },
];
